/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as AuthenticatedPartsBulkRouteImport } from './routes/_authenticated/parts.bulk'
import { Route as AuthenticatedPartsNewRouteImport } from './routes/_authenticated/parts.new'
import { Route as AuthenticatedPartsIdEditRouteImport } from './routes/_authenticated/parts.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/parts/$id',
  path: '/parts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartsBulkRoute = AuthenticatedPartsBulkRouteImport.update({
  id: '/parts/bulk',
  path: '/parts/bulk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartsNewRoute = AuthenticatedPartsNewRouteImport.update({
  id: '/parts/new',
  path: '/parts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartsIdEditRoute =
  AuthenticatedPartsIdEditRouteImport.update({
    id: '/parts/$id/edit',
    path: '/parts/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts/$id': typeof PartsIdRoute
  '/parts/bulk': typeof AuthenticatedPartsBulkRoute
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/parts/$id/edit': typeof AuthenticatedPartsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts/$id': typeof PartsIdRoute
  '/parts/bulk': typeof AuthenticatedPartsBulkRoute
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/parts/$id/edit': typeof AuthenticatedPartsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/parts/$id': typeof PartsIdRoute
  '/_authenticated/parts/bulk': typeof AuthenticatedPartsBulkRoute
  '/_authenticated/parts/new': typeof AuthenticatedPartsNewRoute
  '/_authenticated/parts/$id/edit': typeof AuthenticatedPartsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/parts/$id'
    | '/parts/bulk'
    | '/parts/new'
    | '/parts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalog'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/parts/$id'
    | '/parts/bulk'
    | '/parts/new'
    | '/parts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/catalog'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/parts/$id'
    | '/_authenticated/parts/bulk'
    | '/_authenticated/parts/new'
    | '/_authenticated/parts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PartsIdRoute: typeof PartsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/parts/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parts/bulk': {
      id: '/_authenticated/parts/bulk'
      path: '/parts/bulk'
      fullPath: '/parts/bulk'
      preLoaderRoute: typeof AuthenticatedPartsBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parts/new': {
      id: '/_authenticated/parts/new'
      path: '/parts/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof AuthenticatedPartsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parts/$id/edit': {
      id: '/_authenticated/parts/$id/edit'
      path: '/parts/$id/edit'
      fullPath: '/parts/$id/edit'
      preLoaderRoute: typeof AuthenticatedPartsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartsBulkRoute: typeof AuthenticatedPartsBulkRoute
  AuthenticatedPartsNewRoute: typeof AuthenticatedPartsNewRoute
  AuthenticatedPartsIdEditRoute: typeof AuthenticatedPartsIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartsBulkRoute: AuthenticatedPartsBulkRoute,
  AuthenticatedPartsNewRoute: AuthenticatedPartsNewRoute,
  AuthenticatedPartsIdEditRoute: AuthenticatedPartsIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PartsIdRoute: PartsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
